seed: 9

model:
  name: gpt2
  components_path: components
  components: acdc
    
data:
  path: data
  name: bug
  workers: 4
  val_size: 0.2

tuner:
  epochs: 20
  lr: 1E-4
  warmup: 0
  eps: 1e-8
  momentum: 0.9
  weight_decay: 1E-4
  batch_size: 32
  checkpoint_path: checkpoints
  results_path: results/mitigation
  